-- -- MySQL Script generated by MySQL Workbench
-- -- Thu Jan 23 17:52:16 2020
-- -- Model: New Model    Version: 1.0
-- -- MySQL Workbench Forward Engineering

-- SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
-- SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
-- SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -- -----------------------------------------------------
-- -- Schema mydb
-- -- -----------------------------------------------------

-- -- -----------------------------------------------------
-- -- Schema mydb
-- -- -----------------------------------------------------
-- CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- USE `mydb` ;

-- -- -----------------------------------------------------
-- -- Table `mydb`.`usuarios`
-- -- -----------------------------------------------------
-- CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
--   `id_usuarios` INT NOT NULL AUTO_INCREMENT,
--   `usuario` VARCHAR(45) NULL,
--   `password` VARCHAR(45) NULL,
--   PRIMARY KEY (`id_usuarios`))
-- ENGINE = InnoDB;


-- -- -----------------------------------------------------
-- -- Table `mydb`.`categorias`
-- -- -----------------------------------------------------
-- CREATE TABLE IF NOT EXISTS `mydb`.`categorias` (
--   `id_categorias` INT NOT NULL,
--   `nombre` VARCHAR(45) NULL,
--   PRIMARY KEY (`id_categorias`))
-- ENGINE = InnoDB;


-- -- -----------------------------------------------------
-- -- Table `mydb`.`armas`
-- -- -----------------------------------------------------
-- CREATE TABLE IF NOT EXISTS `mydb`.`armas` (
--   `id_arma` INT NOT NULL AUTO_INCREMENT,
--   `nombre` VARCHAR(45) NULL,
--   `coste` INT NULL,
--   `danio` DOUBLE NULL,
--   `penetracion` DOUBLE NULL,
--   `municion_cargador` INT NULL,
--   `municion_reserva` INT NULL,
--   `recompensa` DOUBLE NULL,
--   `img_arma` VARCHAR(45) NULL,
--   `gif_recoil` VARCHAR(45) NULL,
--   `gif_control` VARCHAR(45) NULL,
--   `gif_ingame` VARCHAR(45) NULL,
--   `categorias_id_categorias` INT NOT NULL,
--   PRIMARY KEY (`id_arma`),
--   INDEX `fk_armas_categorias1_idx` (`categorias_id_categorias` ASC),
--   CONSTRAINT `fk_armas_categorias1`
--     FOREIGN KEY (`categorias_id_categorias`)
--     REFERENCES `mydb`.`categorias` (`id_categorias`)
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION)
-- ENGINE = InnoDB;


-- -- -----------------------------------------------------
-- -- Table `mydb`.`updates`
-- -- -----------------------------------------------------
-- CREATE TABLE IF NOT EXISTS `mydb`.`updates` (
--   `id_update` INT NOT NULL AUTO_INCREMENT,
--   `titulo` VARCHAR(100) NULL,
--   `contenido` TEXT NULL,
--   `fecha` DATETIME NULL,
--   PRIMARY KEY (`id_update`))
-- ENGINE = InnoDB;


-- -- -----------------------------------------------------
-- -- Table `mydb`.`mapas`
-- -- -----------------------------------------------------
-- CREATE TABLE IF NOT EXISTS `mydb`.`mapas` (
--   `id_mapa` INT NOT NULL AUTO_INCREMENT,
--   `nombre` VARCHAR(45) NULL,
--   `img_plano` VARCHAR(45) NULL,
--   `img_logo` VARCHAR(45) NULL,
--   PRIMARY KEY (`id_mapa`))
-- ENGINE = InnoDB;


-- -- -----------------------------------------------------
-- -- Table `mydb`.`tipogranadas`
-- -- -----------------------------------------------------
-- CREATE TABLE IF NOT EXISTS `mydb`.`tipogranadas` (
--   `id_tipogranada` INT NOT NULL,
--   `nombre` VARCHAR(45) NULL,
--   PRIMARY KEY (`id_tipogranada`))
-- ENGINE = InnoDB;


-- -- -----------------------------------------------------
-- -- Table `mydb`.`utilidades`
-- -- -----------------------------------------------------
-- CREATE TABLE IF NOT EXISTS `mydb`.`utilidades` (
--   `id_utilidades` INT NOT NULL AUTO_INCREMENT,
--   `nombre` VARCHAR(100) NULL,
--   `equipo` TINYINT NULL,
--   `imagen` VARCHAR(45) NULL,
--   `video` VARCHAR(45) NULL,
--   `mapas_id_mapa` INT NOT NULL,
--   `granadas_id_granada` INT NOT NULL,
--   PRIMARY KEY (`id_utilidades`),
--   INDEX `fk_utilidades_mapas_idx` (`mapas_id_mapa` ASC) ,
--   INDEX `fk_utilidades_granadas1_idx` (`granadas_id_granada` ASC) ,
--   CONSTRAINT `fk_utilidades_mapas`
--     FOREIGN KEY (`mapas_id_mapa`)
--     REFERENCES `mydb`.`mapas` (`id_mapa`)
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION,
--   CONSTRAINT `fk_utilidades_granadas1`
--     FOREIGN KEY (`granadas_id_granada`)
--     REFERENCES `mydb`.`tipogranadas` (`id_tipogranada`)
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION)
-- ENGINE = InnoDB;


-- -- -----------------------------------------------------
-- -- Table `mydb`.`cajas`
-- -- -----------------------------------------------------
-- CREATE TABLE IF NOT EXISTS `mydb`.`cajas` (
--   `id_caja` INT NOT NULL AUTO_INCREMENT,
--   `nombre` VARCHAR(45) NULL,
--   `imagen_caja` VARCHAR(45) NULL,
--   PRIMARY KEY (`id_caja`))
-- ENGINE = InnoDB;


-- -- -----------------------------------------------------
-- -- Table `mydb`.`skins`
-- -- -----------------------------------------------------
-- CREATE TABLE IF NOT EXISTS `mydb`.`skins` (
--   `id_skin` INT NOT NULL AUTO_INCREMENT,
--   `nombre` VARCHAR(45) NULL,
--   `img_skin` VARCHAR(45) NULL,
--   `armas_id_arma` INT NOT NULL,
--   `cajas_id_caja` INT NOT NULL,
--   PRIMARY KEY (`id_skin`),
--   INDEX `fk_skins_armas1_idx` (`armas_id_arma` ASC) ,
--   INDEX `fk_skins_cajas1_idx` (`cajas_id_caja` ASC) ,
--   CONSTRAINT `fk_skins_armas1`
--     FOREIGN KEY (`armas_id_arma`)
--     REFERENCES `mydb`.`armas` (`id_arma`)
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION,
--   CONSTRAINT `fk_skins_cajas1`
--     FOREIGN KEY (`cajas_id_caja`)
--     REFERENCES `mydb`.`cajas` (`id_caja`)
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION)
-- ENGINE = InnoDB;


-- SET SQL_MODE=@OLD_SQL_MODE;
-- SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
-- SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
